### ISSUE TITLE
CUDA Error

### ISSUE THREAD

**Issue by NapalmCandy** [EleutherAI/vqgan-clip#11]
I am trying to execute the program, but I get some errors, and I can't do. I installed dependencies without errors and checkpoints

`napalm@napalm-Z490-UD:~/Documentos/vqgan-clip-main$ pip install -r requirements.txt
Collecting git+https://github.com/openai/CLIP.git (from -r requirements.txt (line 10))
  Cloning https://github.com/openai/CLIP.git to /tmp/pip-req-build-00rpswv6
  Running command git clone -q https://github.com/openai/CLIP.git /tmp/pip-req-build-00rpswv6
Requirement already satisfied (use --upgrade to upgrade): clip==1.0 from git+https://github.com/openai/CLIP.git in /home/napalm/.local/lib/python3.8/site-packages (from -r requirements.txt (line 10))
Requirement already satisfied: absl-py==0.13.0 in /home/napalm/.local/lib/python3.8/site-packages (from -r requirements.txt (line 1)) (0.13.0)
Requirement already satisfied: aiohttp==3.7.4.post0 in /home/napalm/.local/lib/python3.8/site-packages (from -r requirements.txt (line 2)) (3.7.4.post0)
Requirement already satisfied: antlr4-python3-runtime==4.8 in /home/napalm/.local/lib/python3.8/site-packages (from -r requirements.txt (line 3)) (4.8)
Requirement already satisfied: async-timeout==3.0.1 in /home/napalm/.local/lib/python3.8/site-packages (from -r requirements.txt (line 4)) (3.0.1)
Requirement already satisfied: attrs==21.2.0 in /home/napalm/.local/lib/python3.8/site-packages (from -r requirements.txt (line 5)) (21.2.0)
Requirement already satisfied: backcall==0.2.0 in /home/napalm/.local/lib/python3.8/site-packages (from -r requirements.txt (line 6)) (0.2.0)
Requirement already satisfied: cachetools==4.2.2 in /home/napalm/.local/lib/python3.8/site-packages (from -r requirements.txt (line 7)) (4.2.2)
Requirement already satisfied: certifi==2021.5.30 in /home/napalm/.local/lib/python3.8/site-packages (from -r requirements.txt (line 8)) (2021.5.30)
Requirement already satisfied: chardet==4.0.0 in /home/napalm/.local/lib/python3.8/site-packages (from -r requirements.txt (line 9)) (4.0.0)
Requirement already satisfied: decorator==5.0.9 in /home/napalm/.local/lib/python3.8/site-packages (from -r requirements.txt (line 11)) (5.0.9)
Requirement already satisfied: einops==0.3.0 in /home/napalm/.local/lib/python3.8/site-packages (from -r requirements.txt (line 12)) (0.3.0)
Requirement already satisfied: fsspec==2021.6.1 in /home/napalm/.local/lib/python3.8/site-packages (from -r requirements.txt (line 13)) (2021.6.1)
Requirement already satisfied: ftfy==6.0.3 in /home/napalm/.local/lib/python3.8/site-packages (from -r requirements.txt (line 14)) (6.0.3)
Requirement already satisfied: future==0.18.2 in /usr/lib/python3/dist-packages (from -r requirements.txt (line 15)) (0.18.2)
Requirement already satisfied: grpcio==1.38.1 in /home/napalm/.local/lib/python3.8/site-packages (from -r requirements.txt (line 16)) (1.38.1)
Requirement already satisfied: idna==2.10 in /home/napalm/.local/lib/python3.8/site-packages (from -r requirements.txt (line 17)) (2.10)
Requirement already satisfied: imageio==2.9.0 in /home/napalm/.local/lib/python3.8/site-packages (from -r requirements.txt (line 18)) (2.9.0)
Requirement already satisfied: imageio-ffmpeg==0.4.4 in /home/napalm/.local/lib/python3.8/site-packages (from -r requirements.txt (line 19)) (0.4.4)
Requirement already satisfied: ipython==7.25.0 in /home/napalm/.local/lib/python3.8/site-packages (from -r requirements.txt (line 20)) (7.25.0)
Requirement already satisfied: ipython-genutils==0.2.0 in /home/napalm/.local/lib/python3.8/site-packages (from -r requirements.txt (line 21)) (0.2.0)
Requirement already satisfied: jedi==0.18.0 in /home/napalm/.local/lib/python3.8/site-packages (from -r requirements.txt (line 22)) (0.18.0)
Requirement already satisfied: kornia==0.5.4 in /home/napalm/.local/lib/python3.8/site-packages (from -r requirements.txt (line 23)) (0.5.4)
Requirement already satisfied: Markdown==3.3.4 in /home/napalm/.local/lib/python3.8/site-packages (from -r requirements.txt (line 24)) (3.3.4)
Requirement already satisfied: matplotlib-inline==0.1.2 in /home/napalm/.local/lib/python3.8/site-packages (from -r requirements.txt (line 25)) (0.1.2)
Requirement already satisfied: multidict==5.1.0 in /home/napalm/.local/lib/python3.8/site-packages (from -r requirements.txt (line 26)) (5.1.0)
Requirement already satisfied: numpy==1.21.0 in /home/napalm/.local/lib/python3.8/site-packages (from -r requirements.txt (line 27)) (1.21.0)
Requirement already satisfied: oauthlib==3.1.1 in /home/napalm/.local/lib/python3.8/site-packages (from -r requirements.txt (line 28)) (3.1.1)
Requirement already satisfied: omegaconf==2.1.0 in /home/napalm/.local/lib/python3.8/site-packages (from -r requirements.txt (line 29)) (2.1.0)
Requirement already satisfied: packaging==20.9 in /home/napalm/.local/lib/python3.8/site-packages (from -r requirements.txt (line 30)) (20.9)
Requirement already satisfied: parso==0.8.2 in /home/napalm/.local/lib/python3.8/site-packages (from -r requirements.txt (line 31)) (0.8.2)
Requirement already satisfied: pexpect==4.8.0 in /home/napalm/.local/lib/python3.8/site-packages (from -r requirements.txt (line 32)) (4.8.0)
Requirement already satisfied: pickleshare==0.7.5 in /home/napalm/.local/lib/python3.8/site-packages (from -r requirements.txt (line 33)) (0.7.5)
Requirement already satisfied: Pillow==8.2.0 in /home/napalm/.local/lib/python3.8/site-packages (from -r requirements.txt (line 34)) (8.2.0)
Requirement already satisfied: prompt-toolkit==3.0.19 in /home/napalm/.local/lib/python3.8/site-packages (from -r requirements.txt (line 35)) (3.0.19)
Requirement already satisfied: protobuf==3.17.3 in /home/napalm/.local/lib/python3.8/site-packages (from -r requirements.txt (line 36)) (3.17.3)
Requirement already satisfied: ptyprocess==0.7.0 in /home/napalm/.local/lib/python3.8/site-packages (from -r requirements.txt (line 37)) (0.7.0)
Requirement already satisfied: pyasn1==0.4.8 in /home/napalm/.local/lib/python3.8/site-packages (from -r requirements.txt (line 38)) (0.4.8)
Requirement already satisfied: pyasn1-modules==0.2.8 in /home/napalm/.local/lib/python3.8/site-packages (from -r requirements.txt (line 39)) (0.2.8)
Requirement already satisfied: pyDeprecate==0.3.0 in /home/napalm/.local/lib/python3.8/site-packages (from -r requirements.txt (line 40)) (0.3.0)
Requirement already satisfied: Pygments==2.9.0 in /home/napalm/.local/lib/python3.8/site-packages (from -r requirements.txt (line 41)) (2.9.0)
Requirement already satisfied: pyparsing==2.4.7 in /home/napalm/.local/lib/python3.8/site-packages (from -r requirements.txt (line 42)) (2.4.7)
Requirement already satisfied: pytorch-lightning==1.3.7.post0 in /home/napalm/.local/lib/python3.8/site-packages (from -r requirements.txt (line 43)) (1.3.7.post0)
Requirement already satisfied: PyYAML==5.4.1 in /home/napalm/.local/lib/python3.8/site-packages (from -r requirements.txt (line 44)) (5.4.1)
Requirement already satisfied: regex==2021.4.4 in /home/napalm/.local/lib/python3.8/site-packages (from -r requirements.txt (line 45)) (2021.4.4)
Requirement already satisfied: requests==2.25.1 in /home/napalm/.local/lib/python3.8/site-packages (from -r requirements.txt (line 46)) (2.25.1)
Requirement already satisfied: requests-oauthlib==1.3.0 in /home/napalm/.local/lib/python3.8/site-packages (from -r requirements.txt (line 47)) (1.3.0)
Requirement already satisfied: rsa==4.7.2 in /home/napalm/.local/lib/python3.8/site-packages (from -r requirements.txt (line 48)) (4.7.2)
Requirement already satisfied: six==1.16.0 in /home/napalm/.local/lib/python3.8/site-packages (from -r requirements.txt (line 49)) (1.16.0)
Requirement already satisfied: taming-transformers==0.0.1 in /home/napalm/.local/lib/python3.8/site-packages (from -r requirements.txt (line 50)) (0.0.1)
Requirement already satisfied: tensorboard==2.4.1 in /home/napalm/.local/lib/python3.8/site-packages (from -r requirements.txt (line 51)) (2.4.1)
Requirement already satisfied: tensorboard-plugin-wit==1.8.0 in /home/napalm/.local/lib/python3.8/site-packages (from -r requirements.txt (line 52)) (1.8.0)
Requirement already satisfied: torch==1.9.0 in /home/napalm/.local/lib/python3.8/site-packages (from -r requirements.txt (line 53)) (1.9.0)
Requirement already satisfied: torchaudio==0.9.0 in /home/napalm/.local/lib/python3.8/site-packages (from -r requirements.txt (line 54)) (0.9.0)
Requirement already satisfied: torchmetrics==0.3.2 in /home/napalm/.local/lib/python3.8/site-packages (from -r requirements.txt (line 55)) (0.3.2)
Requirement already satisfied: torch-optimizer==0.1.0 in /home/napalm/.local/lib/python3.8/site-packages (from -r requirements.txt (line 56)) (0.1.0)
Requirement already satisfied: torchvision==0.10.0 in /home/napalm/.local/lib/python3.8/site-packages (from -r requirements.txt (line 57)) (0.10.0)
Requirement already satisfied: tqdm==4.61.1 in /home/napalm/.local/lib/python3.8/site-packages (from -r requirements.txt (line 58)) (4.61.1)
Requirement already satisfied: traitlets==5.0.5 in /home/napalm/.local/lib/python3.8/site-packages (from -r requirements.txt (line 59)) (5.0.5)
Requirement already satisfied: typing-extensions==3.10.0.0 in /home/napalm/.local/lib/python3.8/site-packages (from -r requirements.txt (line 60)) (3.10.0.0)
Requirement already satisfied: urllib3==1.26.6 in /home/napalm/.local/lib/python3.8/site-packages (from -r requirements.txt (line 61)) (1.26.6)
Requirement already satisfied: wcwidth==0.2.5 in /home/napalm/.local/lib/python3.8/site-packages (from -r requirements.txt (line 62)) (0.2.5)
Requirement already satisfied: Werkzeug==2.0.1 in /home/napalm/.local/lib/python3.8/site-packages (from -r requirements.txt (line 63)) (2.0.1)
Requirement already satisfied: yarl==1.6.3 in /home/napalm/.local/lib/python3.8/site-packages (from -r requirements.txt (line 64)) (1.6.3)
Requirement already satisfied: setuptools>=18.5 in /usr/lib/python3/dist-packages (from ipython==7.25.0->-r requirements.txt (line 20)) (45.2.0)
Requirement already satisfied: google-auth<2,>=1.6.3 in /home/napalm/.local/lib/python3.8/site-packages (from tensorboard==2.4.1->-r requirements.txt (line 51)) (1.35.0)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in /home/napalm/.local/lib/python3.8/site-packages (from tensorboard==2.4.1->-r requirements.txt (line 51)) (0.4.6)
Requirement already satisfied: wheel>=0.26; python_version >= "3" in /usr/lib/python3/dist-packages (from tensorboard==2.4.1->-r requirements.txt (line 51)) (0.34.2)
Requirement already satisfied: pytorch-ranger>=0.1.1 in /home/napalm/.local/lib/python3.8/site-packages (from torch-optimizer==0.1.0->-r requirements.txt (line 56)) (0.1.1)
Building wheels for collected packages: clip
  Building wheel for clip (setup.py) ... done
  Created wheel for clip: filename=clip-1.0-py3-none-any.whl size=1369091 sha256=b6fd2947ce04127529aa7039325c06c13a87b989971582c972d15cbced85e69c
  Stored in directory: /tmp/pip-ephem-wheel-cache-pqn14vac/wheels/ab/4f/3a/5e51521b55997aa6f0690e095c08824219753128ce8d9969a3
Successfully built clip`

But when I rund the main.py it give some errors. What it is the problem and how to solve? I am noob on Python 

`napalm@napalm-Z490-UD:~/Documentos/vqgan-clip-main$ python3 main.py -p "Alien World"
/home/napalm/.local/lib/python3.8/site-packages/kornia/augmentation/augmentation.py:1830: DeprecationWarning: GaussianBlur is no longer maintained and will be removed from the future versions. Please use RandomGaussianBlur instead.
  warnings.warn(
/home/napalm/.local/lib/python3.8/site-packages/pytorch_lightning/metrics/__init__.py:43: LightningDeprecationWarning: `pytorch_lightning.metrics.*` module has been renamed to `torchmetrics.*` and split off to its own package (https://github.com/PyTorchLightning/metrics) since v1.3 and will be removed in v1.5
  rank_zero_deprecation(
/home/napalm/.local/lib/python3.8/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:572: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  (np.object, string),
/home/napalm/.local/lib/python3.8/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:573: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  (np.bool, bool),
/home/napalm/.local/lib/python3.8/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:597: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  types_pb2.DT_STRING: np.object,
/home/napalm/.local/lib/python3.8/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:601: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  types_pb2.DT_BOOL: np.bool,
/home/napalm/.local/lib/python3.8/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:618: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  types_pb2.DT_STRING_REF: np.object,
/home/napalm/.local/lib/python3.8/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:623: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  types_pb2.DT_BOOL_REF: np.bool,
/home/napalm/.local/lib/python3.8/site-packages/tensorboard/util/tensor_util.py:113: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.object: SlowAppendObjectArrayToTensorProto,
/home/napalm/.local/lib/python3.8/site-packages/tensorboard/util/tensor_util.py:114: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.bool: SlowAppendBoolArrayToTensorProto,
Working with z of shape (1, 256, 16, 16) = 65536 dimensions.
loaded pretrained LPIPS loss from taming/modules/autoencoder/lpips/vgg.pth
VQLPIPSWithDiscriminator running with hinge loss.
Restored from checkpoints/vqgan_imagenet_f16_16384.ckpt
Traceback (most recent call last):
  File "main.py", line 272, in <module>
    z_min = model.quantize.embedding.weight.min(dim=0).values[None, :, None, None]
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
`

Thanks!

**Comment by StellaAthena** [comment]
Are you sure that you have a CUDA-compatible version of PyTorch installed, and the correct drivers for your GPU?

The core problem here is that your computer doesn’t think that you can run code on GPU. I’m not sure what’s causing that, but CUDA versioning is complicated.

**Comment by NapalmCandy** [comment]
I really don't know what PyTorch is, but as I understand it is installed when I do `pip install -r requirements.txt`, it don't give me errors.

For the nVidia drivers, it was installed automatically to latest version when I installed SO, I am on a clean install of Ubuntu, my GPU it is a RTX3080

**Comment by StellaAthena** [comment]
Try reinstalling PyTorch from [the website directly](https://pytorch.org/)

**Comment by NapalmCandy** [comment]
`pip install torch==1.9.0+cu111 torchvision==0.10.0+cu111 torchaudio==0.9.0 -f https://download.pytorch.org/whl/torch_stable.html`
`pip install ftfy regex tqdm omegaconf pytorch-lightning IPython kornia imageio imageio-ffmpeg einops torch_optimizer`

I tried to install PyTorch from their website, but has the same problem. I tried this two lines commands from another github notebook, and now it works... Now I have a problem with my PSU, do not have enough power for the 3080 and its shotdown, but this is another problem. So I don't fully tried but I think it will works

**Comment by StellaAthena** [comment]
Hmmm…. Well, at a minimum I’m glad you got it working. I didn’t have an issue installing from source on a fresh GPU last week, so I think it must  be a GPU-specific problem. Unfortunately I don’t have access to a 3080, so I can’t really experiment with things. Hopefully this issue will be helpful to the next person though.
